### ISSUE TITLE
Private/Public 

### ISSUE THREAD

**Issue by gknox2017** [futurice/terraform-examples#27]
Hi,
Were these 2 definitions intentionally switched  => private points to public & public points to private ?

https://github.com/futurice/terraform-examples/blob/818250f9d65464c095e7d47f0fe03711a2a7d7ae/aws/wordpress_fargate/vpc.tf#L6

**Comment by sunilkumarmohanty** [comment]
No good point. That is a bug. Will fix it soon.

**Comment by sunilkumarmohanty** [comment]
Issue resolved now
