### ISSUE TITLE
Is there any solution to deploy database easily and create backup while still keeping it flexible. 

### ISSUE THREAD

**Issue by Suresh4587** [futurice/terraform-examples#41]

**Comment by Parth909** [comment]
Hi @Suresh4587 if you are looking for templates to easily spin up databases manually then you can refer this pull request https://github.com/futurice/terraform-examples/pull/42.

Or else you can visit this https://github.com/Parth909/terraform-examples and refer to this commit [18430ae27973902b1d518f34b4fcd3fa2f72bd7a](https://github.com/Parth909/terraform-examples/commit/18430ae27973902b1d518f34b4fcd3fa2f72bd7a)

Using this you can easily deploy a database on AWS along with backup

**Comment by Suresh4587** [comment]
Thanks @Parth909 ! I also need solution for replication but this is a good starting point
