### ISSUE TITLE
Consider aws_static_site in futurice/terraform-utils

### ISSUE THREAD

**Issue by jareware** [futurice/terraform-examples#9]
Since I stumbled across the `static_website_ssl_cloudfront_private_s3` module in this repo, I'd suggest taking a look at https://github.com/futurice/terraform-utils/tree/master/aws_static_site, as it does the same thing, with a few extra niceties!

**Comment by tomlarkworthy** [comment]
Yes I just merged in your repository. Great stuff! History is preserved, though the UI is not good at indicating that, but see the contributors tab for proof.
Utils is aiming for higher quality than we are aiming for here. This repo is for blog posts and copy and paste inspiration.

**Comment by jareware** [comment]
Hmm, I'm not sure that makes total sense to me, since the other repo contains reusable modules (which need to be pulled in and instantiated) and this one contains example code which can just be copy-pasted and `terraform init`ed... but oh well! :smile:
